Repository Leets-Official/Commitato-FE, pull requests merged in 2025-02, with the labels that each got.

#55 fix: env 파일 올라가는지 확인용 파일
  src/pages/myPage/index.tsx
  src/routes/Route.tsx
Labels: fix

#57 #56 Fix: header footer UI 수정
  src/assets/Question.png
  src/assets/Search.png
  src/assets/TopButton.png
  src/assets/ceo_potato_comment.png
  src/assets/circle.png
  src/assets/close.png
  src/assets/comment1.png
  src/assets/comment2.png
  src/assets/comment3.png
  src/assets/comment4.png
  src/assets/commitgrass.png
  src/assets/developer_potato.png
  src/assets/developer_potato_comment.png
  src/assets/footer.png
  src/assets/github.png
  src/assets/githubChar.png
  src/assets/githubLogin.png
  src/assets/icon/ceo_potato.png
  src/assets/icon/footerGithub.svg
  src/assets/introduceModal.png
  src/assets/line.png
  src/assets/ranking_img.png
  src/assets/stupid_potato.png
  src/assets/stupid_potato_comment.png
  src/assets/talking_potato.png
  src/assets/talking_potato_comment.png
  src/assets/yellowButton.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/index.css
  src/main.tsx
  src/pages/myPage/index.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: ♻Refactor, 🎨Style

#64 #63 Fix: footer 수정
  src/components/Footer.tsx
  src/pages/MainPage/index.tsx
Labels: ♻Refactor, 🎨Style

#62 #58 Refactor: 마이페이지 UI 구현
  src/assets/icon/commitFarm.svg
  src/assets/icon/commitStatsLine.svg
  src/assets/icon/firstCommitato.svg
  src/assets/icon/fourthCommitato.svg
  src/assets/icon/myPageGithub.svg
  src/assets/icon/myPageLine.svg
  src/assets/icon/secondCommitato.svg
  src/assets/icon/thirdCommitato.svg
  src/components/Footer.tsx
  src/components/myPage/CommitStats.tsx
  src/components/myPage/CountNumber.tsx
  src/components/myPage/MyCommitFarm.tsx
  src/components/myPage/ProfileCard.tsx
  src/constants/countNumber.constant.ts
  src/constants/index.ts
  src/constants/statsData.constant.ts
  src/contexts/ModalContext.tsx
  src/pages/MainPage/index.tsx
  src/pages/myPage/index.tsx
  src/types/user.d.ts
  tailwind.config.js
Labels: ♻Refactor, 🎨Style

#65 #61 Feat: 공통 모달 UI 구현
  src/assets/icon/close.svg
  src/assets/icon/next.svg
  src/components/Button.tsx
  src/components/modal/CongratModal.tsx
  src/components/modal/WelcomeModal.tsx
  src/components/modal/index.tsx
  src/constants/index.ts
  src/constants/levelMap.constant.ts
  src/contexts/ModalContext.tsx
  src/pages/myPage/index.tsx
Labels: ✨Feature, 🎨Style

#66 #59 Refactor: 랭킹페이지 UI 구현
  src/App.tsx
  src/apis/auth/Login.tsx
  src/assets/icon/ic_ranking_down.svg
  src/assets/icon/ic_ranking_line.svg
  src/assets/icon/ic_ranking_search.svg
  src/assets/icon/ic_ranking_up.svg
  src/components/Header.tsx
  src/components/Ranking/RankingItem.tsx
  src/components/Ranking/RankingList.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/AnimatedText.tsx
  src/pages/Main/components/MainFooter.tsx
  src/pages/Main/components/ParallaxText.tsx
  src/pages/Main/components/ScrollToTopButton.tsx
  src/pages/Main/index.tsx
  src/pages/Ranking/RankingPage.tsx
  src/pages/Ranking/components/RankingItem.tsx
  src/pages/Ranking/components/RankingList.tsx
  src/pages/Ranking/index.tsx
  src/pages/RankingPage/index.tsx
  src/routes/routes.tsx
  tsconfig.app.json
Labels: ♻Refactor, 🎨Style

#69 #68 Feat: GitHub 소셜 로그인 api 연결
  src/apis/auth/Login.tsx
  src/apis/auth/Logout.ts
  src/apis/auth/githubLogin.api.ts
  src/components/Header.tsx
  src/components/main/GithubLogin.tsx
  src/components/main/GithubLoginLoading.tsx
  src/main.tsx
  src/pages/Main/index.tsx
  src/routes/routes.tsx
Labels: 🔗API

#71 #70 Feat: api 인스턴스 작성
  src/apis/api.ts
  src/apis/auth/githubLogin.api.ts
  src/components/main/GithubLoginLoading.tsx
  src/components/modal/WelcomeModal.tsx
  src/pages/Main/index.tsx
Labels: ✨Feature, 🔗API
