Repository Leets-Official/Commitato-FE, pull requests merged in 2025-05, with the labels that each got.

#86 #84 Fix: 랭킹페이지 오류 수정 + 자잘한 UI 수정
  src/App.css
  src/components/Ranking/Pagination.tsx
  src/components/Ranking/RankingList.tsx
  src/components/main/SectionMain.tsx
  src/components/main/SectionWrapper.tsx
  src/pages/Main/index.tsx
  src/pages/myPage/index.tsx
  src/types/ranking.d.ts
Labels: 🐛BugFix, ♻Refactor, 🎨Style

#88 #87 Refactor: 랭킹페이지 수정사항 반영
  src/apis/ranking/ranking.api.ts
  src/components/Ranking/RankingItem.tsx
  src/components/Ranking/RankingItemSkeleton.tsx
  src/components/Ranking/RankingList.tsx
  src/types/ranking.d.ts
Labels: ♻Refactor, 🎨Style

#90 #89 Refactor: qa 사항 반영
  src/apis/auth/githubLogin.api.ts
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/main/GithubLoginButton.tsx
  src/components/main/GithubLoginLoading.tsx
  src/components/myPage/CommitStats.tsx
  src/components/myPage/CountNumber.tsx
  src/components/myPage/MyCommitFarm.tsx
  src/components/myPage/ProfileCard.tsx
  src/components/myPage/UpdateButton.tsx
  src/pages/myPage/index.tsx
  tsconfig.eslint.json
Labels: ♻Refactor

#93 #91 Refactor: 2차 qa 사항 반영
  src/apis/myPage/updateButton.api.ts
  src/components/main/GithubLoginLoading.tsx
  src/components/modal/LoginLoadingModal.tsx
  src/components/myPage/UpdateButton.tsx
  src/pages/Main/index.tsx
Labels: 🐛BugFix, ♻Refactor, 🔗API
